# Module manifest for module 'PowerShell-Core-Compatibility-Alias'
# Generated by: Joseph Warren
# Generated on: 2/6/2019

@{
    RootModule        = 'PSCM.psm1'
    ModuleVersion     = '0.3.2'
    GUID              = '4e1c82d2-7c23-410f-841d-dce52dbc630e'
    Author            = 'Joseph Warren'
    CompanyName       = 'Unknown'
    Copyright         = '(c) Joseph Warren. All rights reserved.'
    Description       = 'Powershell module to aid in deploying updates from SCCM.'
    FunctionsToExport = @('Connect-PSCMServer',
        'Add-PSCMObjectToCollection',
        'Clear-PSCMSoftwareUpdateGroup',
        'Copy-PSCMSoftwareUpdateGroup',
        'Export-PSCMUsageInformation',
        'Find-PSCMUpdate',
        'Get-PSCMSoftwareUpdateProductCategory',
        'Merge-PSCMSoftwareUpdateGroup',
        'Merge-PSCMSoftwareUpdateGroup',
        'Save-PSCMUsageData',
        'Set-PSCMSoftwareUpdateGroupDeploymentDeadline',
        'Sync-PSCMMetaData',
        'Get-PSCMServiceConnectionPointMode',
        'Get-PSCMLicenseKey',
        'Restart-PSCMCCMAgent' )
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
    # CompatiblePSEditions = @()
    # PowerShellVersion = ''
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # CLRVersion = ''
    # ProcessorArchitecture = ''
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()
    PrivateData       = @{
        PSData = @{
            Tags       = @('SCCM')
            LicenseUri = 'https://github.com/luzkenin/PSCM/blob/master/LICENSE'
            ProjectUri = 'https://github.com/luzkenin/PSCM'
            # IconUri = ''
            # ReleaseNotes = ''
        }
    }
    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''
}

